"""
File: plot.py

Description:
  Plot the data from the Fortran program for each x value.

Dependencies:
- None

Since:
  - 03/2025

Authors:
  - Pedro C. Delbem <pedrodelbem@usp.br>
"""

# Import necessary libraries
import matplotlib.pyplot as plt  # type: ignore
import numpy as np # type: ignore
import os

def read_table(file_path):
    """
    Reads the table generated by the Fortran program and stores it in a Python dictionary of dictionaries.
    
    The dictionary has the form:
    {x1: {N: [N1, N2, ...], series_e_neg_x: [val1, val2, ...], series_e_x_inv: [val1, val2, ...], fortran_val: [val1, val2, ...]},
     x2: {...},
     ...}
    """
    
    # Initialize data dictionary and current_x variable
    data = {}
    current_x = None
    
    # Read the table
    with open(file_path, 'r') as file:

        # Loop over the lines
        for line in file:

            # Split the line
            parts = line.split()

            # Check if the line is a header
            if len(parts) == 2 and parts[0] == 'x:':

                # If it is, update the current_x variable
                current_x = float(parts[1])

                # Create a new entry in the data dictionary with the current x value
                data[current_x] = {'N': [], 'series_e_minus_x': [], 'series_e_x_inverse': [], 'fortran_value': []}

            # Check if the line is a data line
            elif len(parts) == 5 and parts[0] == 'N:':

                # If it is, append the data to the corresponding entry in the data dictionary
                N = int(parts[1])
                series_e_minus_x = float(parts[2])
                series_e_x_inverse = float(parts[3])
                fortran_value = float(parts[4])
                
                # Append the data
                data[current_x]['N'].append(N)
                data[current_x]['series_e_minus_x'].append(series_e_minus_x)
                data[current_x]['series_e_x_inverse'].append(series_e_x_inverse)
                data[current_x]['fortran_value'].append(fortran_value)
    
    return data

def plot_data(data, output_folder="images"):
    """
    Plot the data from the Fortran program for each x value and save the plots in a specified folder.

    Parameters
    ----------
    data : dict
        A dictionary of dictionaries, where each key is a value of x and
        the corresponding value is another dictionary with keys 'N',
        'series_e_minus_x', 'series_e_x_inverse', and 'fortran_value'.
        The values of these keys are lists of the same length, where each
        index corresponds to a value of N.

    output_folder : str
        The folder where the images will be saved. Default is "images".
    """

    # Create the output folder if it does not exist
    os.makedirs(output_folder, exist_ok=True)

    # Loop over the data
    for x, values in data.items():

        # Extract the data
        N = values['N']
        series_e_minus_x = values['series_e_minus_x']
        series_e_x_inverse = values['series_e_x_inverse']
        fortran_value = values['fortran_value']
        
        # Plot the data
        plt.figure(figsize=(8, 5))
        plt.plot(N, series_e_minus_x, 'o-', label=r'Série $e^{-x}$')
        plt.plot(N, series_e_x_inverse, 's-', label=r'1 / Série $e^x$')
        plt.plot(N, fortran_value, 'd-', label='Fortran function')
        
        plt.xscale('log')
        plt.xlabel('N')
        plt.ylabel('Valor da Série')
        plt.title(f'Convergência para x = {x}')
        plt.legend()
        plt.grid(True)

        # Save the plot in the specified folder
        file_name = os.path.join(output_folder, f"grafico_x_{x}.png")
        plt.savefig(file_name)

        # Close the plot
        plt.close()

# Read the table
data = read_table('exponential_taylor_series.txt')

# Plot the data and save the images in "images" folder
plot_data(data)